# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ branch-* ]
  pull_request:
    branches: [ branch-* ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Setup Python 2.7
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 2.7
    - name: Setup _JAVA_OPTIONS
      run: export _JAVA_OPTIONS="-Xmx2048m -XX:MaxPermSize=512m -Djava.awt.headless=true"
    - name: Download & Setup Python setuptools
      run: wget https://files.pythonhosted.org/packages/25/5d/cc55d39ac39383dd6e04ae80501b9af3cc455be64740ad68a4e12ec81b00/setuptools-0.6c11-py2.7.egg#md5=fe1f997bc722265116870bc7919059ea && sh setuptools-0.6c11-py2.7.egg
    - name: Setting the Version
      run: mvn versions:set-property -Dproperty=revision -DnewVersion=2.7.5.0.0
    - name: Build with Maven
      run: mvn -B clean install package rpm:rpm --am -pl ambari-server -DskipTests -Drat.skip=true -Dpython.ver="python >= 2.6" -Preplaceurl
